CASM-2670: Fix annotations and make steps more flexible.
Cray-HPE/cms-meta-tools pull request #16
Opened 2021-11-12 16:56 UTC by rbak-hpe

## Summary and Scope

- Fixes the additional annotations so they don't overwrite what's already in the chart
- Fixes the branch parsing and a script so they can be run outside of Jenkins. (We are not using the functionality immediately, but this will enable us to run these tools as part of the github workflow in the future)

## Issues and Related PRs

* Needed for our CASM-2670 PRs to build correctly.

## Testing

### Tested on:

Build changes only

### Test description:

Setup a workflow that ran the meta-tools and verified the output

## Risks and Mitigations

None

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2021-11-12 18:11 UTC, mharding-hpe requested changes

2021-11-12 18:11 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +        if grep "global:" "$dir/values.yaml"; then
For all of these greps where we are checking for the presence of a given field, it seems like it would be safer to do:
`grep "^\s*global:"`

That ensures that by some weird chance the string "global:" appears on a line in another context, like inside of a string value.

2021-11-12 18:11 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +                sed -i "$dir/values.yaml" -e "s/appVersion:.*/appVersion: ${APP_VERSION}/"
And similar to the safer grep comment above, the sed replace command seems like it would be safer like this:
`"s/^\(\sappVersion:\).*/\1 ${APP_VERSION}/"`

2021-11-15 17:18 UTC, rbak-hpe commented on version.py
> -        # DST Build pipelines don't allow us to query the name of the version all the time.
@jsl-hpe Could I get your review on this code?  I assume this comment about the AttributeError isn't relevant since we aren't building through DST pipelines anymore.

2021-11-15 17:29 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +                sed -i "$dir/values.yaml" -e "s/appVersion:.*/appVersion: ${APP_VERSION}/"
fixed

2021-11-15 17:29 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +        if grep "global:" "$dir/values.yaml"; then
fixed

2021-11-15 17:29 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +
fixed

2021-11-15 17:29 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +            sed -i "$dir/Chart.yaml" -e "s/appVersion:.*/appVersion: ${APP_VERSION}/"
fixed

2021-11-15 17:29 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +                sed -i "$dir/values.yaml" -e "s/^global\s*$/global:\n  appVersion: ${APP_VERSION}/"
fixed

2021-11-15 17:30 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +                sed -i "$dir/values.yaml" -e "s/appVersion:.*/appVersion: ${APP_VERSION}/"
fixed

2021-11-15 17:30 UTC, rbak-hpe commented on scripts/update-chart-app-version.sh
> +#!/bin/bash
fixed

2021-11-15 17:30 UTC, rbak-hpe commented on git_info/git_info.sh
> +        sed -e "s,^annotations:\s*$,annotations:\n  git/branch: \"${GIT_BRANCH}\"\n  git/commit-date: \"${GIT_COMMIT_DATE}\"\n  git/commit-id: \"${GIT_COMMIT_ID}\"," -i "${target}" ||
fixed

2021-11-18 16:27 UTC, mharding-hpe requested changes

2021-11-18 16:27 UTC, mharding-hpe commented on git_info/git_info.sh
> +        mv ${target}.tmp ${target}
I'd change this to "run_cmd mv ..."

That way it will exit in error if the mv command fails.

2021-11-18 16:27 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +            if grep "appVersion:" "$dir/values.yaml"; then
The same change to the grep command when searching for "global:" should be made here -- we don't want to match on the off chance that appVersion: appears as part of some field valuje.

2021-11-18 16:27 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +        if grep "appVersion:" "$dir/Chart.yaml"; then
Same grep change should be made here too

2021-11-18 16:29 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +        if grep "global:" "$dir/values.yaml"; then
This specific grep command is resolved, but not the other similar ones. But I've made separate review comments for those now, so I'll mark this conversation resolved.

2021-11-18 16:31 UTC, mharding-hpe requested changes

2021-11-18 16:31 UTC, mharding-hpe commented on scripts/update-chart-app-version.sh
> +            sed -e "s/appVersion:.*/appVersion: ${APP_VERSION}/" "$dir/Chart.yaml" > "$dir/Chart.yaml.tmp"
The same sed replace change needs to be made here as on line 41

2021-11-18 19:12 UTC, mharding-hpe approved these changes

2021-11-18 20:59 UTC, jsl-hpe approved these changes

2021-11-18 21:22 UTC, jsl-hpe commented on utils/pyyaml.sh
> +        --index-url https://arti.dev.cray.com:443/artifactory/api/pypi/pypi-remote/simple \
Do we have an algol source for this?

2021-11-18 21:24 UTC, mharding-hpe commented on utils/pyyaml.sh
> +        --index-url https://arti.dev.cray.com:443/artifactory/api/pypi/pypi-remote/simple \
Not for the DST-provided Python stuff, no. Only for the Python modules we build ourselves.

2021-11-18 21:30 UTC, merged